# Generated by Django 2.2.4 on 2019-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
